### ISSUE TITLE
Error while running pred functions

### ISSUE THREAD

**Issue by sugarcane29** [themains/pydomains#7]
Hi.
I get the following error while running the pred functions: "AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
I'm using the following packages:
pydomains (0.2.0)
Keras (2.3.1)
tensorflow (2.3.0)

Code:
```
import pandas as pd
from pydomains import *

df = pd.read_csv('D:/Google Drive/Datasets/Comscore 2018/domains_2018.zip')
df = df[1:100]

df_shalla   = pred_shalla(df, domain_names = 'domain_name')
df_toulouse = pred_toulouse(df, domain_names = 'domain_name')
```

Console Output:
********************
```
df_toulouse = pred_toulouse(df, domain_names = 'domain_name')
Using cached Toulouse model data from local (E:\WPy64-3771\settings\.pydomains\toulouse_cat_lstm_others_2017.h5)...
Using cached Toulouse vocab data from local (E:\WPy64-3771\settings\.pydomains\toulouse_cat_vocab_others_2017.csv)...
Using cached Toulouse names data from local (E:\WPy64-3771\settings\.pydomains\toulouse_cat_names_others_2017.csv)...
Loading Toulouse model, vocab and names data file...
Traceback (most recent call last):

  File "<ipython-input-11-f19b92001d44>", line 1, in <module>
    df_toulouse = pred_toulouse(df, domain_names = 'domain_name')

  File "E:\WPy64-3771\python-3.7.7.amd64\lib\site-packages\pydomains\pred_toulouse.py", line 89, in pred_toulouse
    model, vocab, cats = load_model_data(year, latest)

  File "E:\WPy64-3771\python-3.7.7.amd64\lib\site-packages\pydomains\pred_toulouse.py", line 58, in load_model_data
    model = load_model(model_path)

  File "E:\WPy64-3771\python-3.7.7.amd64\lib\site-packages\keras\engine\saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)

  File "E:\WPy64-3771\python-3.7.7.amd64\lib\site-packages\keras\engine\saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)

  File "E:\WPy64-3771\python-3.7.7.amd64\lib\site-packages\keras\engine\saving.py", line 274, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)

  File "E:\WPy64-3771\python-3.7.7.amd64\lib\site-packages\keras\engine\saving.py", line 627, in model_from_config
    return deserialize(config, custom_objects=custom_objects)

  File "E:\WPy64-3771\python-3.7.7.amd64\lib\site-packages\keras\layers\__init__.py", line 168, in deserialize
    printable_module_name='layer')

  File "E:\WPy64-3771\python-3.7.7.amd64\lib\site-packages\keras\utils\generic_utils.py", line 147, in deserialize_keras_object
    list(custom_objects.items())))

  File "E:\WPy64-3771\python-3.7.7.amd64\lib\site-packages\keras\engine\sequential.py", line 302, in from_config
    model.add(layer)

  File "E:\WPy64-3771\python-3.7.7.amd64\lib\site-packages\keras\engine\sequential.py", line 166, in add
    layer(x)

  File "E:\WPy64-3771\python-3.7.7.amd64\lib\site-packages\keras\backend\tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)

  File "E:\WPy64-3771\python-3.7.7.amd64\lib\site-packages\keras\engine\base_layer.py", line 446, in __call__
    self.assert_input_compatibility(inputs)

  File "E:\WPy64-3771\python-3.7.7.amd64\lib\site-packages\keras\engine\base_layer.py", line 310, in assert_input_compatibility
    K.is_keras_tensor(x)

  File "E:\WPy64-3771\python-3.7.7.amd64\lib\site-packages\keras\backend\tensorflow_backend.py", line 695, in is_keras_tensor
    if not is_tensor(x):

  File "E:\WPy64-3771\python-3.7.7.amd64\lib\site-packages\keras\backend\tensorflow_backend.py", line 703, in is_tensor
    return isinstance(x, tf_ops._TensorLike) or tf_ops.is_dense_tensor_like(x)

AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'
```

**************************

**Comment by soodoku** [comment]
the following commit https://github.com/themains/pydomains/commit/de9509c94b6791d9ba3ee2e375701822773c6f53 should solve it
